stages:
  - lint
  - build

lint:
  stage: lint
  image: node:12.2.0-alpine
  before_script:
    - npm install
  script:
    - npx eslint ./src
  allow_failure: true

build:
  services:
    - docker:dind
  image: docker:stable
  stage: build
  variables:
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  before_script:
    - cat $FIREBASE_CONFIG > ./src/config/firebaseAuthConfig.js
    - cat $RCLONE_CONFIG > ./config/rclone.conf
  script:
    - echo "Building image"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -t $IMAGE_NAME
    - docker push $IMAGE_NAME
    - docker tag $IMAGE_NAME $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  except:
    - master
    - configuracao-ci

build stable:
  services:
    - docker:dind
  image: docker:stable
  stage: build
  variables:
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:stable"
  before_script:
    - cat $FIREBASE_CONFIG > ./src/config/firebaseAuthConfig.js
    - cat $RCLONE_CONFIG > ./config/rclone.conf
  script:
    - echo "Building image"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build . -t $IMAGE_NAME
    - docker push $IMAGE_NAME
  only:
    - master
    - configuracao-ci
