version: '3'
services:
    backend:
        container_name: backend
        environment:
            - DATABASE_URL=mongodb://mongo/miaAjudaDB
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        depends_on:
            - mongo
        volumes:
            - .:/app
            - /app/node_modules
    mongo:
        container_name: mongo
        image: mongo
