version: "3"
services:
    mgob:
        container_name: mgob
        environment:
            - MONGODB_USERNAME=${MONGODB_USERNAME}
            - MONGODB_PASSWORD=${MONGODB_PASSWORD}
        image: stefanprodan/mgob:edge
        command: ./mgob -LogLevel=info
        volumes:
            - ./config:/config
            - /mgob/storage:/storage
            - /mgob/tmp:/tmp
            - /mgob/data:/data
        depends_on:
            - mongo
